"""Static coverage check: every chart generated in fit/report/sections/charts.py
must have a corresponding <canvas id="..."> in dashboard.html.

This guards against silent drift where charts are generated server-side but
never rendered (e.g., orphaned chart-rpe that we wired up retroactively).
"""

import re
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
CHARTS_PY = REPO / "fit" / "report" / "sections" / "charts.py"
DASHBOARD_HTML = REPO / "fit" / "report" / "templates" / "dashboard.html"

# Charts built inline in the template (not via _all_charts), so they're
# expected to have canvases but no entry in charts.py. Keep this short and
# documented — every entry should explain WHY the chart bypasses _all_charts.
INLINE_TEMPLATE_CHARTS = {
    # Built inline from `prediction_trend` data passed by the generator,
    # not via _all_charts. It's the small Race Anchor card preview.
    "chart-pred-trend",
}


def _generated_chart_ids() -> set[str]:
    text = CHARTS_PY.read_text()
    return set(re.findall(r'"id":\s*"(chart-[a-z0-9-]+)"', text))


def _canvas_chart_ids() -> set[str]:
    text = DASHBOARD_HTML.read_text()
    return set(re.findall(r'<canvas[^>]+id="(chart-[a-z0-9-]+)"', text))


class TestDashboardChartCoverage:
    """Static check: charts.py and dashboard.html agree on chart IDs."""

    def test_every_generated_chart_has_a_canvas(self):
        """Every chart emitted by _all_charts must render in the template.

        If this fails, either add the canvas to dashboard.html or remove the
        dead chart code from charts.py. Don't suppress this — silent orphans
        accumulate and confuse future readers.
        """
        generated = _generated_chart_ids()
        rendered = _canvas_chart_ids()
        orphans = generated - rendered
        assert not orphans, (
            f"Charts generated by fit/report/sections/charts.py but with no "
            f"<canvas id> in dashboard.html: {sorted(orphans)}. "
            f"Either wire up the canvas or remove the dead code."
        )

    def test_no_canvases_without_a_generator(self):
        """Every canvas in the template must have a generator OR be an
        explicitly-allowed inline chart.
        """
        generated = _generated_chart_ids()
        rendered = _canvas_chart_ids()
        unexplained = rendered - generated - INLINE_TEMPLATE_CHARTS
        assert not unexplained, (
            f"Canvases in dashboard.html with no generator entry in "
            f"charts.py and not in INLINE_TEMPLATE_CHARTS: {sorted(unexplained)}. "
            f"Add to charts.py, build inline and add to INLINE_TEMPLATE_CHARTS, "
            f"or remove the canvas."
        )

    def test_at_least_one_chart_exists(self):
        """Sanity: the regexes shouldn't return empty (would mask everything)."""
        assert _generated_chart_ids(), "No chart IDs found in charts.py — regex broken?"
        assert _canvas_chart_ids(), "No canvas IDs found in dashboard.html — regex broken?"
